name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - Examples/**
      - README.md
      - LICENSE
  pull_request:
    branches: [ main ]
    paths-ignore:
      - Examples/**
      - README.md
      - LICENSE

jobs:
  run-macos:
    name: ${{ matrix.subcommand }} with Xcode ${{ matrix.xcode }} on macOS
    runs-on: macos-15
    strategy:
      matrix:
        xcode: ["16.0"]
        subcommand: ["Build"]
    steps:
    - uses: actions/checkout@v4
    - name: ${{ matrix.subcommand }}
      run: |
        xcodebuild -version
        swift --version
        swift package --version
        subcommand=`echo ${{ matrix.subcommand }} | tr '[:upper:]' '[:lower:]'`
        make ${subcommand}-debug
      env:
        DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app
